name: Build VyOS Image
on:
  push:
    branches: [ 1.3 ]
  pull_request:
    branches: [ 1.3 ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Cache Build
        uses: actions/cache@v2
        with:
          path: ./vyos-build/build/cache/
          key: 1.3

      - name: Build Images
        run: sudo ./build.sh

      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: ./vyos-build/build/live-image-amd64.hybrid.iso
          tag_name: $TAG_NAME
        env:
          TAG_NAME: build-${{ steps.date.outputs.date }}
